services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
      - jenkins
    networks:
      - ssadagu-network
    restart: always

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8081:8080" # 로컬 호스트에서는 8081로 직접 접속 가능
      - "50000:50000"
    volumes:
      - jenkins_home_local:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - ssadagu-network
    restart: always

  backend:
    build:
      context: ./Ssadagu-Backend
      dockerfile: Dockerfile
    env_file:
      - ./Ssadagu-Backend/.env
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ssadagu-network
    restart: always

  frontend:
    build:
      context: ./Ssadagu-Frontend
      dockerfile: Dockerfile
    env_file:
      - ./Ssadagu-Frontend/.env.local
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ssadagu-network
    restart: always

networks:
  ssadagu-network:
    driver: bridge

volumes:
  jenkins_home_local:
