spring.application.name=ssadagu
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=300000
# JWT Key (최소 256bit - 32글자 이상의 Secret Key를 환경변수에서 주입받음)
jwt.secret=${JWT_SECRET}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# SSAFY 금융망 API 설정
ssafy.api.base-url=https://finopenapi.ssafy.io/ssafy/api/v1
ssafy.api.institution-code=00100
ssafy.api.fintech-app-no=001
ssafy.api.key=${SSAFY_API_KEY}
ssafy.api.user-key=${SSAFY_API_USER_KEY}

# AWS S3 Settings
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.s3.bucket=${S3_BUCKET_NAME}
# Maximum upload file size (Optional)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# GMS API Settings (AI Metadata Generation)
gms.api.key=${GMS_API_KEY}
gms.api.endpoint=https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions

# Proxy Forwarding
server.forward-headers-strategy=native
