spring.application.name=ssadagu

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=S14P21A202
